/**
 * export-seed.js — Sinh src/data/seed.generated.ts cho app React (GĐ 3).
 *
 * LÀM GÌ:
 *   Eval 2 module legacy (utils.js + seed-data.js) trong Node (stub window.VocabApp)
 *   → gọi VA.buildSeedEntries() / VA.buildZhSeedEntries() → xuất mảng WordEntry
 *   chuẩn (senses dùng meaning map) thành file TS cho app React import.
 *
 * LỢI ÍCH:
 *   - Không phải copy 204KB seed bằng tay, không lệch shape.
 *   - Nguồn duy nhất vẫn là seed-data.js (legacy) — sửa seed ở đó rồi chạy lại tool.
 *
 * CÁCH CHẠY:
 *   node tools/export-seed.js [--out <file>]
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LEGACY_JS = path.join(ROOT, 'apps', 'web', 'public', 'legacy', 'js');
const OUT_DEFAULT = path.join(ROOT, 'apps', 'web', 'src', 'data', 'seed.generated.ts');

const outArg = process.argv.indexOf('--out');
const OUT = outArg >= 0 ? path.resolve(process.cwd(), process.argv[outArg + 1]) : OUT_DEFAULT;

// Stub môi trường (giống _e2e.js) — chỉ cần window + VocabApp
const windowStub = { VocabApp: {} };
global.window = windowStub;

function evalFile(file) {
  const code = fs.readFileSync(file, 'utf-8');
  // indirect eval → chạy ở global scope (IIFE thấy `window`)
  (0, eval)(code);
}

evalFile(path.join(LEGACY_JS, 'utils.js'));
evalFile(path.join(LEGACY_JS, 'seed-data.js'));

const VA = windowStub.VocabApp;
const en = VA.buildSeedEntries();
const zh = VA.buildZhSeedEntries();

const header = `/**
 * GENERATED by tools/export-seed.js — KHÔNG SỬA TAY.
 * Sinh từ apps/web/public/legacy/js/seed-data.js (buildSeedEntries / buildZhSeedEntries).
 * Chạy lại tool sau khi thay đổi seed:  node tools/export-seed.js
 */
import type { WordEntry } from '@english/shared';

`;

const body = `export const SEED_EN: WordEntry[] = ${JSON.stringify(en, null, 1)};\n\n` +
  `export const SEED_ZH: WordEntry[] = ${JSON.stringify(zh, null, 1)};\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body);
console.log(`OK: ${en.length} từ EN + ${zh.length} từ ZH → ${path.relative(ROOT, OUT)}`);
